// ── Kalani Compass — Static Data ──────────────────────────────────────────────
// All static constants: courses, requirements, pathways, colors, defaults.
// To add/edit courses: edit COURSES array or update Supabase table.
// GRADE_MAX lives in utils.js (used alongside gradeSlots logic).

const DEPT_ORDER = [
  "English","Social Studies","Mathematics","Science",
  "Health & PE","CTE","World Language","Fine Arts","Miscellaneous","Off Campus"
];

const GRAD_REQUIREMENTS = [
  { id:"english",  label:"English",           required:4.0, color:"#C84B31",
    breakdown:["ELA 1 (1.0)","ELA 2 (1.0)","ELA 3 or AP English 3 (1.0)","ELA 4 or AP English 4 (1.0)"] },
  { id:"ss",       label:"Social Studies",    required:4.0, color:"#7C3AED",
    breakdown:["Participation in Democracy (0.5)","Modern History of Hawaiʻi (0.5)","US History/Gov (1.0)","World History (1.0)","Grade 12 SS elective (1.0)"] },
  { id:"math",     label:"Mathematics",       required:3.0, color:"#059669",
    breakdown:["Geometry (1.0)","Algebra 1 (1.0)","Algebra 2 or other math elective (1.0)"] },
  { id:"science",  label:"Science",           required:3.0, color:"#D97706",
    breakdown:["Biology 1 (1.0)","Science electives (2.0)"] },
  { id:"wlfa",     label:"World Lang / Fine Arts / CTE", required:2.0, color:"#0891B2",
    breakdown:["2 credits in one area: World Language, Fine Arts, or CTE pathway sequence"] },
  { id:"pe",       label:"Physical Education",required:1.0, color:"#10B981",
    breakdown:["PE Lifetime Fitness (0.5) — required","PE Lifetime Activities (0.5) — required"] },
  { id:"health",   label:"Health",            required:0.5, color:"#EC4899",
    breakdown:["Health Today & Tomorrow (0.5)"] },
  { id:"ptp",      label:"Personal Transition Plan",required:0.5, color:"#84CC16",
    breakdown:["Personal Transition Plan (0.5)"] },
  { id:"electives",label:"Electives",         required:6.0, color:"#F97316",
    breakdown:["Any subject area — overflow from subject buckets also counts (6.0 credits)"] },
];

const COURSES = [

  // ── ENGLISH ────────────────────────────────────────────────────────────────
  { id:"ELA1",    code:"LCY1010", name:"English Language Arts 1",             dept:"English", credits:1.0, gradeLevel:[9],       prereqs:[],           gradCategory:"english",  gradCredits:1.0,
    desc:"Year course. Foundation reading, writing, oral communication, literature, and language study. All high school content standards and benchmarks are addressed. Heterogeneous class.",
    tips:"Required for all 9th graders. Builds your core literacy skills for everything that follows." },
  { id:"ELA2",    code:"LCY2010", name:"English Language Arts 2",             dept:"English", credits:1.0, gradeLevel:[10],      prereqs:["ELA1"],      gradCategory:"english",  gradCredits:1.0,
    desc:"Year course. Balanced reading, writing, oral communication. World literature focus. All Hawaiʻi state benchmarks addressed. Heterogeneous class.",
    tips:"World literature focus. Great opportunity to explore diverse writing styles and global voices." },
  { id:"ELA3",    code:"LCY3010", name:"English Language Arts 3",             dept:"English", credits:1.0, gradeLevel:[11],      prereqs:["ELA2"],      gradCategory:"english",  gradCredits:1.0,
    desc:"Year course. Strategic language use; informational and literary texts. Research, critical reading, and analytical writing. All 11th-grade benchmarks addressed.",
    tips:"Heavy research component. Strong note-taking habits help. AP English Language is the honors alternative." },
  { id:"ELA4",    code:"LCY4010", name:"English Language Arts 4",             dept:"English", credits:1.0, gradeLevel:[12],      prereqs:["ELA3"],      gradCategory:"english",  gradCredits:1.0,
    desc:"Year course. Precision in written and spoken language, argumentation, and debate. British, European, African, and local works. Multiple learning opportunities and assessment choices.",
    tips:"Argumentation skills transfer directly to college essays. AP English Literature is the honors alternative." },
  { id:"AP_ENG3", code:"LAY6010", name:"AP English Language Arts 3", subtitle:"AP English Language & Composition",   dept:"English", credits:1.0, gradeLevel:[11],      prereqs:["ELA2"],      gradCategory:"english",  gradCredits:1.0, isAP:true,
    desc:"Year course. College-level writing, rhetoric, and composition. Taken instead of ELA 3. AP exam required in May (~$96). Parent/guardian info session required. Cannot be taken concurrently with AP Seminar. Once enrolled, student must remain for the year.",
    tips:"Excellent preparation for college writing. Requires strong commitment — you cannot drop after starting." },
  { id:"AP_ENG4", code:"LAY6100", name:"AP English Language Arts 4", subtitle:"AP English Literature & Composition",  dept:"English", credits:1.0, gradeLevel:[12],      prereqs:["ELA3"],      gradCategory:"english",  gradCredits:1.0, isAP:true,
    desc:"Year course. College-level literature and composition. World and British literature focus, rhetorical theory. AP exam required in May. Open to any willing senior. Once enrolled, must remain for the year.",
    tips:"Great pairing if you took AP Language junior year. Deepens literary analysis skills." },
  { id:"AP_SEM",  code:"XAP1000", name:"AP Seminar",                          dept:"English", credits:1.0, gradeLevel:[10,11],   prereqs:[],            gradCategory:"electives", gradCredits:1.0, isAP:true,
    desc:"Year course. Critical thinking, research, problem-solving, argumentation, and multimedia communication. Part of AP Capstone diploma program. Leads to AP Research. Categorized as a General Elective at Kalani. Cannot be taken concurrently with AP English Language. Must remain for full year.",
    tips:"Take this before AP Research — it is the required first step. Strong preparation for any research-intensive major." },
  { id:"AP_RES",  code:"XAP1100", name:"AP Research",                         dept:"English", credits:1.0, gradeLevel:[11,12],   prereqs:["AP_SEM"],    gradCategory:"electives", gradCredits:1.0, isAP:true,
    desc:"Year course. Design and conduct a year-long independent research investigation. Students demonstrate scholarly understanding through three performance tasks. AP Capstone diploma program. Must remain for full year.",
    tips:"Requires AP Seminar as prerequisite. Strong independent work ethic and time management essential." },

  // ── SOCIAL STUDIES ─────────────────────────────────────────────────────────
  { id:"PID",      code:"CGU1100",  name:"Participation in Democracy",         dept:"Social Studies", credits:0.5, gradeLevel:[9],  prereqs:[],          gradCategory:"ss", gradCredits:0.5,
    desc:"Semester course (Semester 1, Grade 9). Required for graduation. Democratic government, federal/state/local structures, rights and responsibilities. Students practice contacting public officials and applying political science tools.",
    tips:"Taken Semester 1 of 9th grade, paired with Modern History of Hawaiʻi." },
  { id:"MHH",      code:"CHR1100",  name:"Modern History of Hawaiʻi",          dept:"Social Studies", credits:0.5, gradeLevel:[9],  prereqs:[],          gradCategory:"ss", gradCredits:0.5,
    desc:"Semester course (Semester 2, Grade 9). Required for graduation. Hawaiʻi history since 1898: monarchy, annexation, sugar industry, Martial Law, statehood, and current events.",
    tips:"Taken Semester 2 of 9th grade, paired with Participation in Democracy." },
  { id:"USH",      code:"CHU1100",  name:"United States History & Government", dept:"Social Studies", credits:1.0, gradeLevel:[10], prereqs:["PID","MHH"],gradCategory:"ss", gradCredits:1.0,
    desc:"Year course. Chronological survey of U.S. history from 1877 to the present. Major events, geography, individuals, and ideas of American heritage.",
    tips:"10th grade core social studies. AP US History is the honors alternative." },
  { id:"AP_USH",   code:"CHA6100",  name:"AP United States History",           dept:"Social Studies", credits:1.0, gradeLevel:[10], prereqs:["PID","MHH"],gradCategory:"ss", gradCredits:1.0, isAP:true,
    desc:"Year course. College-level two-semester survey of U.S. history, analytical skills, and evidence-based argumentation. AP exam required in May. Essay submission and Kalani AP contact required.",
    tips:"Writing-intensive. Strong essay skills essential. One of the most essay-demanding AP courses offered." },
  { id:"WH",       code:"CHW1100",  name:"World History & Culture",            dept:"Social Studies", credits:1.0, gradeLevel:[11], prereqs:["USH"],     gradCategory:"ss", gradCredits:1.0,
    desc:"Year course. Political, economic, geographic, and social events shaping world history. Early civilizations through current world events. Primary and secondary source analysis.",
    tips:"11th grade core. AP World History is the honors alternative." },
  { id:"AP_WH",    code:"CHA6300",  name:"AP World History",                   dept:"Social Studies", credits:1.0, gradeLevel:[11], prereqs:["USH"],     gradCategory:"ss", gradCredits:1.0, isAP:true,
    desc:"Year course. College-level world history from 8000 BCE to present. Six historical periods. AP exam required in May. Kalani AP contact required.",
    tips:"Writing-intensive. Great if you enjoy history and can manage college-level reading demands." },
  { id:"ECON",     code:"CSD2500",  name:"Economics",                          dept:"Social Studies", credits:0.5, gradeLevel:[12], prereqs:["WH"],     gradCategory:"ss", gradCredits:0.5,
    desc:"Semester course (Grade 12). Concepts and analytical tools to understand major economic problems facing the nation and world. Economic skills for post-high school life. Must be paired with Psychology or AP Macroeconomics (both taken same year).",
    tips:"⚠️ Must be taken alongside Psychology OR AP Macroeconomics — they share the same year as a two-semester pair." },
  { id:"PSYCH",    code:"CSD2200",  name:"Psychology",                         dept:"Social Studies", credits:0.5, gradeLevel:[12], prereqs:["WH"],     gradCategory:"ss", gradCredits:0.5,
    desc:"Semester course (Grade 12). Why humans behave as they do. Theory vs. fact, research methods, learning theories, behavior disorders. Paired with Economics as the standard Grade 12 social studies year course.",
    tips:"⚠️ Must be taken alongside Economics — both are required as a two-semester pairing." },
  { id:"AP_MACRO", code:"CSA6200",  name:"AP Macroeconomics",                  dept:"Social Studies", credits:0.5, gradeLevel:[12], prereqs:["WH"],     gradCategory:"ss", gradCredits:0.5, isAP:true, concurrentOk:["ECON"],
    desc:"Two-semester AP course (0.5/0.5 credits). College-level economics: understanding economic systems, international trade, finance, and government policies. AP exam required in May (~$96). Must be paired with (taken alongside) Economics (CSD2500A).",
    tips:"⚠️ Must be taken alongside Economics. AP Macro + Economics together fulfill the Grade 12 SS requirement." },
  { id:"AP_PSYCH", code:"CSA2500",  name:"AP Psychology",                      dept:"Social Studies", credits:1.0, gradeLevel:[12], prereqs:["WH"],     gradCategory:"ss", gradCredits:1.0, isAP:true,
    desc:"Year course. Equivalent to introductory college psychology. Biological, behavioral, cognitive, humanistic, and socio-cultural perspectives. Specific topics: methodology, neuroscience, development, intelligence, disorders. AP exam required in May.",
    tips:"One of the most popular AP courses at Kalani. Excellent for medicine, social work, or education majors." },

  // ── MATHEMATICS ────────────────────────────────────────────────────────────
  { id:"GEO",     code:"MGX1150", name:"Geometry",                             dept:"Mathematics", credits:1.0, gradeLevel:[9],      prereqs:[],              gradCategory:"math", gradCredits:1.0,
    desc:"Year course. All incoming Kalani freshmen enroll in Geometry (SY 2022-23+). Plane and solid Euclidean geometry. Compass and straightedge required. Upperclassmen who have Algebra 1 credit but not yet Geometry also take this course.",
    tips:"Compass and straightedge required from day one. Teacher or department chair recommendation needed for all math courses." },
  { id:"ALG1",    code:"MAX1155", name:"Algebra 1",                            dept:"Mathematics", credits:1.0, gradeLevel:[10],     prereqs:["GEO"],         gradCategory:"math", gradCredits:1.0,
    desc:"Year course. Basic algebraic structure and mathematical problem solving. Foundation for all subsequent math courses and other department subjects. All Algebra 1 students are concurrently enrolled in Algebra 1 Workshop on alternating days.",
    tips:"Algebra 1 Workshop (co-requisite) provides alternating-day support. If you received a C or below in Geometry, Workshop enrollment is mandatory." },
  { id:"ALG1W",   code:"MSW10091", name:"Algebra 1 Workshop",                 dept:"Mathematics", credits:1.0, gradeLevel:[10],     prereqs:["GEO"],         gradCategory:"math", gradCredits:1.0,
    desc:"Co-requisite course taken alongside Algebra 1. Meets on alternating days to provide support, remediation, reinforcement, and enrichment. Mandatory for students who received a C or below in Geometry, or by teacher recommendation. Credit awarded by semester.",
    tips:"⚠️ This is a co-requisite — you cannot take it independently. It is automatically assigned alongside Algebra 1. Add it to your plan only if you expect to need it." },
  { id:"ALG2",    code:"MAX1200", name:"Algebra 2",                            dept:"Mathematics", credits:1.0, gradeLevel:[10,11],  prereqs:["ALG1"],  gradCategory:"math", gradCredits:1.0,
    desc:"Year course. Builds upon and extends Algebra 1. Required for UH Mānoa admission and most comparable 4-year universities. Students with 8th grade Algebra 1 credit may take this after completing Geometry.",
    tips:"Need credit in Algebra 1 and Geometry. If you completed Algebra 1 in 8th grade, you can take this in 10th grade right after Geometry." },
  { id:"TRIG",    code:"MCX1010", name:"Trigonometry / Pre-Calculus",          dept:"Mathematics", credits:1.0, gradeLevel:[11,12],  prereqs:["ALG2"],        gradCategory:"math", gradCredits:1.0,
    gradeReqs:{"ALG2":"B or better"},
    desc:"Two-semester year course (0.5 cr each semester). Trigonometry in Semester 1, Pre-Calculus in Semester 2. For students highly proficient in algebra and geometry. Placement test required.",
    tips:"B or better in Algebra 2 recommended. Strongly recommended for students planning STEM or pre-med majors. Prerequisite for Calculus and AP Calculus." },
  { id:"ALG3",    code:"MAX1310", name:"Algebra 3 / Statistics",               dept:"Mathematics", credits:1.0, gradeLevel:[11,12],  prereqs:["ALG2"],        gradCategory:"math", gradCredits:1.0,
    gradeReqs:{"ALG2":"C or better"},
    desc:"Two-semester year course (0.5 cr per semester). Advanced algebra of real and complex numbers (Semester 1), then descriptive and inferential statistics (Semester 2). Placement test required.",
    tips:"Good alternative to Trig/PreCal for non-STEM paths. C or better in Algebra 2. Counts toward Academic and STEM Honors beyond-Algebra 2 requirement." },
  { id:"CALC",    code:"MCX1040", name:"Calculus",                             dept:"Mathematics", credits:1.0, gradeLevel:[12],     prereqs:["TRIG"],        gradCategory:"math", gradCredits:1.0,
    gradeReqs:{"TRIG":"B or better"},
    desc:"Year course. Limits as the foundation of calculus, differentiation, and integration. Signed AP-style contract required. Placement test required.",
    tips:"B or better in Trig/PreCal and all previous math courses, plus teacher recommendation and placement test." },
  { id:"AP_CALC", code:"MCA1040", name:"AP Calculus",                          dept:"Mathematics", credits:1.0, gradeLevel:[12],     prereqs:["TRIG"],        gradCategory:"math", gradCredits:1.0, isAP:true,
    gradeReqs:{"TRIG":"B or better"},
    desc:"Year course. College-level calculus. Students MUST take the AP Mathematics Exam in May (~$99). Placement test and signed AP contract required. One of the most valued AP courses for STEM admissions.",
    tips:"B or better in Trig/PreCal, placement test, and teacher recommendation required. Highly regarded by college admissions." },
  { id:"AP_STATS",code:"MCA1050", name:"AP Statistics",                        dept:"Mathematics", credits:1.0, gradeLevel:[11,12],  prereqs:["ALG2"],        gradCategory:"math", gradCredits:1.0, isAP:true,
    gradeReqs:{"ALG2":"B or better"},
    desc:"Year course. Collecting, analyzing, and drawing conclusions from data. Four themes: data exploration, planning a study, anticipating patterns, and statistical inference. AP exam required in May. Incoming seniors preferred; B or better in Algebra 2 and teacher recommendation required.",
    tips:"Great for students interested in social sciences, medicine, or business. Less computation-heavy than Calculus. Counts toward Academic/STEM Honors math requirement." },
  { id:"ICMATH",  code:"MIC1200", name:"Introduction to College Mathematics",  dept:"Mathematics", credits:1.0, gradeLevel:[12],     prereqs:["ALG2"],        gradCategory:"math", gradCredits:1.0,
    desc:"Year course. Prepares seniors for non-STEM college math. Topics from Algebra, Functions, Geometry, and Statistics. Mathematical modeling and quantitative reasoning. Students may earn UH system placement credit based on grades and SBAC scores.",
    tips:"For seniors on non-STEM paths. Requires Geometry + Algebra 2 credit and current math teacher recommendation. Counts toward Academic and STEM Honors beyond-Algebra 2 requirement." },

  // ── SCIENCE ────────────────────────────────────────────────────────────────
  { id:"ISCI",     code:"SAH2003",  name:"Integrated Science",                dept:"Science", credits:1.0, gradeLevel:[9],       prereqs:[],                       gradCategory:"science", gradCredits:1.0, teacherSigRequired:true,
    desc:"Year course for 9th graders. Integrates Scientific Method, Biology, and Chemistry. Energy transformations, electromagnetic waves, periodic table, cellular structure, photosynthesis, and cellular respiration. Teacher signature required.",
    tips:"Take this if you don't yet have Algebra 1 credit. Biology 1 (Grade 9 track) is available if you already have Algebra 1." },
  { id:"BIO1_9",   code:"SLH22039", name:"Biology 1 (Grade 9 track)",         dept:"Science", credits:1.0, gradeLevel:[9],       prereqs:["ALG1"],                 gradCategory:"science", gradCredits:1.0, teacherSigRequired:true,
    desc:"Year course for 9th graders who have already completed Algebra 1 (typically in 8th grade). Life processes, genetics, evolution, and ecology. Fulfills the required Biology 1 graduation credit. Teacher signature required.",
    tips:"Only available to 9th graders who completed Algebra 1 in middle school. Fulfills Biology 1 graduation requirement a year early." },
  { id:"BIO1_10",  code:"SLH2203",  name:"Biology 1",                         dept:"Science", credits:1.0, gradeLevel:[10],      prereqs:[],                       gradCategory:"science", gradCredits:1.0, teacherSigRequired:true,
    desc:"Year course. Fundamental life processes, relationships between structure and function, genetics, evolution, and ecology. Required for graduation. Teacher signature required.",
    tips:"Required graduation credit. If you took Integrated Science in 9th grade, this is your Biology 1." },
  { id:"CHEM",     code:"SPH3503",  name:"Chemistry",                         dept:"Science", credits:1.0, gradeLevel:[10,11],   prereqs:["ALG1"],                 gradCategory:"science", gradCredits:1.0, teacherSigRequired:true,
    desc:"Year course. College-preparatory introduction to chemistry using an interdisciplinary approach. Open to students who have completed Algebra 1. Teacher signature required.",
    tips:"Good for students not planning science-focused careers. Opens the path to AP Environmental Science and AP Biology." },
  { id:"HCHEM",    code:"SPH3503H", name:"Honors Chemistry",                  dept:"Science", credits:1.0, gradeLevel:[10,11],   prereqs:["ALG1"],  concurrentOk:["ALG2"], gradCategory:"science", gradCredits:1.0, teacherSigRequired:true,
    gradeReqs:{"ALG1":"B or better"},
    desc:"Year course. Rigorous college-prep chemistry for students planning science-related careers. Mathematical formulation, experimental problems, and independent study. Requires B or better in Algebra 1, and concurrent enrollment in (or completion of) Algebra 2. Teacher signature required.",
    tips:"B or better in Algebra 1 required. Must be taking Algebra 2 concurrently or have already completed it. Strongly recommended before AP Chemistry." },
  { id:"AP_BIO",   code:"SLH8003",  name:"AP Biology",                        dept:"Science", credits:1.0, gradeLevel:[11,12],   prereqs:["BIO1_10","CHEM"],       gradCategory:"science", gradCredits:1.0, isAP:true, teacherSigRequired:true,
    gradeReqs:{"BIO1_10":"B or better"},
    desc:"Year course. First-year college biology. Lab work equivalent to college level. Organisms, genetics, evolution, ecology, biochemistry. AP exam required in May. B or higher in Biology 1 and completion of Chemistry required.",
    tips:"One of the most demanding AP courses. Honors Chemistry strongly recommended as preparation." },
  { id:"AP_CHEM",  code:"SPH5003",  name:"AP Chemistry",                      dept:"Science", credits:1.0, gradeLevel:[11,12],   prereqs:["HCHEM","ALG2"],         gradCategory:"science", gradCredits:1.0, isAP:true, teacherSigRequired:true,
    gradeReqs:{"HCHEM":"B or better"},
    desc:"Year course. First-year college chemistry. Atomic theory, bonding, equilibrium, kinetics, thermodynamics. AP exam required. Open to students with Algebra 2 or higher and Honors Chemistry with B or better.",
    tips:"Need B or better in Honors Chemistry. One of the most rigorous AP sciences at Kalani." },
  { id:"PHYS",     code:"SPH5603",  name:"Physics",                           dept:"Science", credits:1.0, gradeLevel:[11,12],   prereqs:["ALG2"],    gradCategory:"science", gradCredits:1.0, teacherSigRequired:true,
    desc:"Year course. College-preparatory physics: force, mass, motion, energy, sound, light, electricity, and magnetism. Requires Geometry, Algebra 1, and Algebra 2. Teacher signature required.",
    tips:"Good for engineering interest without full AP rigor. Need all three math prerequisites completed." },
  { id:"AP_PHYS",  code:"SPH7505",  name:"AP Physics 1",                      dept:"Science", credits:1.0, gradeLevel:[11,12],   prereqs:[], concurrentOk:["TRIG"], gradCategory:"science", gradCredits:1.0, isAP:true, teacherSigRequired:true,
    desc:"Year course. Algebra-based college physics. Kinematics, dynamics, energy, momentum, rotation, harmonic motion. AP exam required in May. Open to students currently enrolled in OR who have completed Trigonometry/Pre-Calculus.",
    tips:"Can be taken while concurrently taking Trig/Pre-Calculus. Very math and reasoning intensive. Strong self-discipline is key." },
  { id:"AP_ENVSCI",code:"SIH3903",  name:"AP Environmental Science",          dept:"Science", credits:1.0, gradeLevel:[11,12],   prereqs:["BIO1_10","CHEM"],       gradCategory:"science", gradCredits:1.0, isAP:true, teacherSigRequired:true,
    desc:"Year course. Earth's systems and human-environment interactions. Ecosystems, populations, pollution, land/water use, global climate change. AP exam required in May.",
    tips:"Popular AP choice. Less math-heavy than AP Chem or Physics. Great for environmentally-minded students." },
  { id:"HPHYS",    code:"SLH7503",  name:"Human Physiology 1",                dept:"Science", credits:1.0, gradeLevel:[11,12],   prereqs:["BIO1_10"],              gradCategory:"science", gradCredits:1.0, teacherSigRequired:true,
    desc:"Year course. Second-year biology. In-depth study of human anatomy: circulation, respiration, digestion, muscular, skeletal, nervous, and reproductive systems. Teacher signature required.",
    tips:"Great for students interested in health, nursing, or medicine careers. Completion of Biology 1 required." },
  { id:"MARINE",   code:"SEH2503",  name:"Marine Science",                    dept:"Science", credits:1.0, gradeLevel:[10,11,12],prereqs:["BIO1_10"],              gradCategory:"science", gradCredits:1.0, teacherSigRequired:true,
    desc:"Year course. Physical and biological aspects of the marine environment. Marine animal and plant anatomy, interactions, and man's relationship with the ocean. College-preparatory. Open to grades 10–12 with Biology 1 credit.",
    tips:"Very popular Hawaiʻi-relevant science elective. Completion of Biology 1 required." },
  { id:"STEM_CAP", code:"XAT1000",  name:"STEM Capstone",                     dept:"Science", credits:1.0, gradeLevel:[11,12],   prereqs:[],                       gradCategory:"electives", gradCredits:1.0, teacherSigRequired:true,
    desc:"Year course. Self-directed, project-based. Students research, design, build, test, and deliver a solution to a community need. Required for STEM Honors Recognition Certificate (class of 2016 and beyond). Teacher signature required.",
    tips:"Required for STEM Honors. Demands strong self-direction and time management. Great for college applications." },

  // ── HEALTH & PE ────────────────────────────────────────────────────────────
  { id:"HEALTH",       code:"HLE1000", name:"Health: Today and Tomorrow",     dept:"Health & PE", credits:0.5, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"health", gradCredits:0.5,
    desc:"Semester course. Required 0.5 credit for graduation. Promoting safety, mental/emotional health, personal health and wellness, healthy eating and physical activity, tobacco-free lifestyle, alcohol and drug-free lifestyle, and sexual health.",
    tips:"Required for graduation. Usually taken in 9th or 10th grade." },
  { id:"PE_LF",        code:"PEP1005", name:"PE Lifetime Fitness",            dept:"Health & PE", credits:0.5, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"pe",     gradCredits:0.5,
    desc:"Semester course. Required 0.5 credit for graduation. Aquatics, aerobics, spinning/cycling, running/walking, circuit training, core functional training, and weight training. Cardio test/heart rate monitor assessments.",
    tips:"Required for graduation (one of two required PE credits). Usually taken 9th or 10th grade." },
  { id:"PE_LA",        code:"PEP1010", name:"PE Lifetime Activities",         dept:"Health & PE", credits:0.5, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"pe",     gradCredits:0.5,
    desc:"Semester course. Required 0.5 credit for graduation. Life-long recreational activities: Ultimate Frisbee, Speedball, Indoor Soccer, Water Explorations, Horseshoes, Team Handball. Biathlon fitness assessment (2-mile run + 600-yard swim).",
    tips:"Required for graduation (second of two required PE credits). Pairs with PE Lifetime Fitness to fulfill 1.0 PE requirement." },
  { id:"TEAM_SPORTS1", code:"PTP1640", name:"Team Sports 1",                  dept:"Health & PE", credits:0.5, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"pe",     gradCredits:0.5,
    desc:"Semester course. NOT repeatable. Physical movement forms, team sports skills, and sportsmanship. Adventure games, basketball, volleyball, soccer, softball, water polo, flag football. Rules, strategy, and teamwork.",
    tips:"Can only be taken once. Great PE elective if you enjoy competitive team sports." },
  { id:"TEAM_SPORTS2", code:"PTP1650", name:"Team Sports 2",                  dept:"Health & PE", credits:0.5, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"pe",     gradCredits:0.5,
    desc:"Semester course. NOT repeatable. Continues Team Sports 1 content with more complex team sport skills, advanced movement patterns, and competitive play. Rules, strategy, and teamwork.",
    tips:"Can only be taken once. A separate course from Team Sports 1 — both can be planned if you enjoy team sports." },
  { id:"WT",           code:"PWP1210", name:"Weight Training (Years 1 & 2)",  dept:"Health & PE", credits:0.5, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"pe",     gradCredits:0.5, repeatable:true,
    desc:"Semester course (repeatable across years 1 and 2, up to 4 semesters total). Systematically introduces weight training techniques, philosophies, and safety. Each phase increases workload. Cardiac health running included.",
    tips:"Can be added multiple times across your 4 years. Complete all 4 semesters (Years 1 and 2) before enrolling in Body Conditioning." },
  { id:"BODY_COND",    code:"PBP1110", name:"Body Conditioning",              dept:"Health & PE", credits:0.5, gradeLevel:[11,12],       prereqs:["WT"], gradCategory:"pe", gradCredits:0.5,
    desc:"Semester course. Year 3 of the weight training sequence. Isometric, isotonic, plyometric, aerobic, anaerobic, and resistance training. Diet, vitamins, supplements, and body composition covered.",
    tips:"Year 3 of the WT sequence — complete Weight Training Years 1 and 2 (all 4 semesters) before enrolling." },

  // ── MISCELLANEOUS ──────────────────────────────────────────────────────────
  { id:"PTP",          code:"TGG1105", miscType:"General", name:"Personal Transition Plan",       dept:"Miscellaneous", credits:0.5, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"ptp", gradCredits:0.5,
    desc:"Semester course. Required 0.5 credit for graduation. Career planning, life goals, and educational planning. Credit not awarded until student documents meeting Hawaii CTE Career Planning standards in Grades 9–12.",
    tips:"Required for graduation. Best taken early so you can plan the rest of high school around your goals." },
  { id:"COMMUNITY_SVC",code:"XLH2001", miscType:"General", name:"Community Service",             dept:"Miscellaneous", credits:0.5, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"electives", gradCredits:0.5, repeatable:true,
    desc:"A minimum of 60 hours of verified community service with the same group/organization earns 0.5 elective credit. No letter grade assigned. May be repeated, but no more than 1.0 total credit (120 hours) may be applied toward graduation. Consult your counselor before hours begin.",
    tips:"Max 1.0 credit toward graduation. Must consult counselor prior to starting service hours. Great for college applications." },
  { id:"CTL",          code:"XLP1015CTL1", miscType:"General", name:"Center for Tomorrow's Leaders (CTL)", dept:"Miscellaneous", credits:1.0, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"electives", gradCredits:1.0, teacherSigRequired:true,
    desc:"Year course (two semesters: XLP1015CTL1 + XLP1015CTL2). Statewide leadership program. Students take on real-world challenges, lead community projects, and connect with peers across Hawaiʻi. Teacher signature required.",
    tips:"More than a class — a statewide movement. Great for students who want to lead and create community impact." },
  { id:"LEADERSHIP",   code:"XLP2000", miscType:"General",    name:"Leadership Training",        dept:"Miscellaneous", credits:1.0, gradeLevel:[10,11,12], prereqs:[], gradCategory:"electives", gradCredits:1.0, repeatable:true,
    desc:"Year course (repeatable Grades 10/11/12). Group processes, leadership skills, planning and coordinating class and committee projects. Codes: Grade 10 = XLP2000, Grade 11 = XLP3000, Grade 12 = XLP4000, KAS = XLP5000.",
    tips:"Required for class officers and KAS officers. Strongly recommended for all student leaders. Can repeat across Grade 10–12." },
  { id:"NEWSWRITE1",   code:"LJY8210", miscType:"Journalism",    name:"Newswriting 1",              dept:"Miscellaneous", credits:1.0, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"electives", gradCredits:1.0,
    desc:"Year course. Introduction to school newspaper staff. Study of newspaper structure, functions, and production roles. Writing, interviewing, and publishing journalism.",
    tips:"Year 1 of the Newswriting sequence. Great for students interested in journalism, writing, or media." },
  { id:"NEWSWRITE2",   code:"LJY8300", miscType:"Journalism",    name:"Newswriting 2",              dept:"Miscellaneous", credits:1.0, gradeLevel:[9,10,11,12], prereqs:["NEWSWRITE1"], gradCategory:"electives", gradCredits:1.0,
    desc:"Year course. Advanced writing, production, and editorial responsibilities on the school newspaper staff.",
    tips:"Build toward senior editorial roles. Each year earns another elective credit." },
  { id:"NEWSWRITE3",   code:"LJY8400", miscType:"Journalism",    name:"Newswriting 3",              dept:"Miscellaneous", credits:1.0, gradeLevel:[9,10,11,12], prereqs:["NEWSWRITE2"], gradCategory:"electives", gradCredits:1.0,
    desc:"Year course. Advanced journalism: in-depth reporting, layout design, and leadership on the newspaper staff.",
    tips:"Students begin taking on staff leadership and editorial direction." },
  { id:"NEWSWRITE4",   code:"LJY8500", miscType:"Journalism",    name:"Newswriting 4",              dept:"Miscellaneous", credits:1.0, gradeLevel:[9,10,11,12], prereqs:["NEWSWRITE3"], gradCategory:"electives", gradCredits:1.0,
    desc:"Year course. Senior-level journalism. Students lead production and mentor younger staff members.",
    tips:"Top tier of the newspaper program. Strong college application value for journalism and communication majors." },
  { id:"PATHWAY_EXP1", code:"TGG1101", miscType:"General",    name:"Pathway Exploration 1",      dept:"Miscellaneous", credits:0.5, gradeLevel:[11,12], prereqs:[], gradCategory:"electives", gradCredits:0.5,
    desc:"Semester course (Semester 1). Based on Project Wayfinder. Introspective work: discover personal purpose, core values, and meaning. Must be taken with Pathway Exploration 2 in the same year.",
    tips:"Recommended for juniors and seniors. Both semesters (TGG1101 + TGG1102) must be taken together in the same year." },
  { id:"PATHWAY_EXP2", code:"TGG1102", miscType:"General",    name:"Pathway Exploration 2",      dept:"Miscellaneous", credits:0.5, gradeLevel:[11,12], prereqs:["PATHWAY_EXP1"], gradCategory:"electives", gradCredits:0.5,
    desc:"Semester course (Semester 2). Students implement a passion project in the community tied to purpose discovered in Semester 1.",
    tips:"Community engagement and passion project required. Must take alongside Pathway Exploration 1 in the same year." },
  { id:"TRANS_HS",     code:"TGG1103", miscType:"General",    name:"Transitions to High School",  dept:"Miscellaneous", credits:0.5, gradeLevel:[9], prereqs:[], gradCategory:"electives", gradCredits:0.5,
    desc:"Semester course. Assists 9th graders' transition to high school: study habits, self-image, reading, writing, and computer literacy. DOES NOT count toward the 2-credit CTE requirement. Counts as elective credit only.",
    tips:"Only for incoming 9th graders. Does NOT count toward CTE graduation requirement — elective credit only." },
  { id:"TEACHER_ASST", code:"TIK5930", miscType:"General",    name:"Teacher Assistant for Technology Integration", dept:"Miscellaneous", credits:1.0, gradeLevel:[10,11,12], prereqs:[], gradCategory:"electives", gradCredits:1.0, teacherSigRequired:true,
    desc:"Year course. Students assist teacher with technology integration in the classroom. Teacher signature required.",
    tips:"Good way to develop tech and communication skills. Teacher signature required." },
  { id:"YEARBOOK1",    code:"XYY8610", miscType:"Journalism",    name:"Yearbook 1",                 dept:"Miscellaneous", credits:1.0, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"electives", gradCredits:1.0, teacherSigRequired:true,
    desc:"Year course. Layout design, interviewing, caption writing, photography, and meeting deadlines. Independent thinking required. After-school work may be required. Teacher signature required.",
    tips:"After-school work may be needed to meet deadlines. Great design and writing portfolio experience." },
  { id:"YEARBOOK2",    code:"XYY8630", miscType:"Journalism",    name:"Yearbook 2",                 dept:"Miscellaneous", credits:1.0, gradeLevel:[9,10,11,12], prereqs:["YEARBOOK1"], gradCategory:"electives", gradCredits:1.0, teacherSigRequired:true,
    desc:"Year course. More complex design and photography roles. Section editor responsibilities. After-school work may be required. Teacher signature required.",
    tips:"Returning staff take on section editor and design lead roles." },
  { id:"YEARBOOK3",    code:"XYY8650", miscType:"Journalism",    name:"Yearbook 3",                 dept:"Miscellaneous", credits:1.0, gradeLevel:[9,10,11,12], prereqs:["YEARBOOK2"], gradCategory:"electives", gradCredits:1.0, teacherSigRequired:true,
    desc:"Year course. Senior-level yearbook production. Students lead the book's design, photography, and editorial direction. Teacher signature required.",
    tips:"Leadership role in the yearbook. Strong portfolio piece for design and communications." },

  // ── CTE — AFNR ─────────────────────────────────────────────────────────────
  { id:"AFNR1",      code:"TAO1000", name:"Foundations of Agriculture, Food & Natural Resources", dept:"CTE", ctePath:"AFNR", credits:1.0, gradeLevel:[9,10,11], prereqs:[], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year 1. Introductory course for the AFNR pathway. Informs students about agriculture careers and the role of agriculture in the 21st century. Foundation for Animal Systems, Food Systems, Natural Resources Business, and Natural Resources Management programs. Students gain foundational knowledge of ecosystems, plant systems, animal systems, and reproduction.",
    tips:"Year 1 of AFNR pathway. Leads to two separate branches: Animal Systems or Agriculture Business." },
  { id:"SAS",        code:"TAS2000", name:"Small Animal Systems",             dept:"CTE", ctePath:"AFNR", credits:1.0, gradeLevel:[10,11,12], prereqs:["AFNR1"], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    desc:"Year 2 — Animal Systems branch. Anatomy and physiological systems of small and specialty animals. For students interested in veterinary, vet tech, or animal-related professions. Teacher signature/recommendation required.",
    tips:"Together with AFNR Foundations, completes the 2-credit CTE graduation requirement." },
  { id:"LAS",        code:"TAS3000", name:"Large Animal Systems",             dept:"CTE", ctePath:"AFNR", credits:1.0, gradeLevel:[11,12],    prereqs:["SAS"], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    desc:"Year 3 — Animal Systems branch. Anatomy and care of large animals. For students interested in veterinary or animal-related professions. Requires Foundations of AFNR AND Small Animal Systems. Teacher signature/recommendation required.",
    tips:"Continues the Animal Systems track. Both prerequisite courses required." },
  { id:"WBL_ANIMAL", code:"TAS4000", name:"Animal Systems: Work-Based Learning", dept:"CTE", ctePath:"AFNR", credits:1.0, gradeLevel:[12], prereqs:["LAS"], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    desc:"Year 4 — Animal Systems capstone. Work-based learning experience to develop professional and ethical understanding. Demonstrates mastery of academic and technical skills. Requires Foundations AND Large Animal Systems. Teacher signature/recommendation required.",
    tips:"Capstone of the Animal Systems track. Year 4 of the sequence." },
  { id:"AGRI_BIZ1",  code:"TAO2000", name:"Principles of Agriculture, Agri-Business & Food Systems", dept:"CTE", ctePath:"AFNR", credits:1.0, gradeLevel:[10,11,12], prereqs:["AFNR1"], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    desc:"Year 2 — Agriculture Business branch. Plant and animal structural anatomy, systems physiology, genetics, and biotechnology. Agricultural production business practices, economics of production, Hawaiian land stewardship traditions. Teacher signature/recommendation required.",
    tips:"Together with AFNR Foundations, completes the 2-credit CTE requirement. Leads to Agriculture Production & Agri-Business courses." },
  { id:"AGRI_PROD",  code:"TAB3000", name:"Agriculture Production & Agri-Business", dept:"CTE", ctePath:"AFNR", credits:1.0, gradeLevel:[11,12], prereqs:["AGRI_BIZ1"], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    desc:"Year 3 — Agriculture Business branch. Plant and animal structural anatomy, systems physiology, genetics, and biotechnology continued. Requires Foundations AND Principles of Agriculture. Teacher signature/recommendation required.",
    tips:"Year 3 of the Agriculture Business track." },
  { id:"AGRI_PROD2", code:"TAB4000", name:"Agriculture Production & Agri-Business 2", dept:"CTE", ctePath:"AFNR", credits:1.0, gradeLevel:[12], prereqs:["AGRI_PROD"], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    desc:"Year 4 — Agriculture Business capstone. Prepares students for the world of natural resources business by combining finance, accounting, marketing, and ethical practices. All three prerequisite courses required. Teacher signature/recommendation required.",
    tips:"Capstone of the Agriculture Business track. Year 4 of the sequence." },

  // ── CTE — BUSINESS ─────────────────────────────────────────────────────────
  { id:"BIZ1", code:"TBB1000", name:"Foundations of Business & Marketing",    dept:"CTE", ctePath:"Business", credits:1.0, gradeLevel:[9,10,11], prereqs:[], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year 1. Introductory course about careers in various sectors of business and basic business concepts. Foundation for the Entrepreneurship program of study.",
    tips:"Year 1 of Business pathway. Good for students interested in entrepreneurship or business careers." },
  { id:"ENT1", code:"TBE2000", name:"Entrepreneurship 1",                     dept:"CTE", ctePath:"Business", credits:1.0, gradeLevel:[10,11,12], prereqs:["BIZ1"], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year 2. Management, finance, and marketing principles in an entrepreneurship context. Starting and running a business. Prerequisite: Foundations of Business and Marketing.",
    tips:"Together with Foundations of Business, completes the 2-credit CTE requirement." },
  { id:"ENT2", code:"TBE3000", name:"Entrepreneurship 2",                     dept:"CTE", ctePath:"Business", credits:1.0, gradeLevel:[11,12],    prereqs:["ENT1"], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year 3. Operations, finance, accounting, marketing, and ethical practices for small businesses. Prepares students for the world of business.",
    tips:"Year 3 of the Business track. Requires both Foundations and Entrepreneurship 1." },

  // ── CTE — ARTS & MEDIA (Digital Design branch) ─────────────────────────────
  { id:"DIGPHOTO1",  code:"TCC1000DP", name:"Foundations of Creative Media (Digital Photography 1)", dept:"CTE", ctePath:"Arts & Media", credits:1.0, gradeLevel:[9,10,11], prereqs:[], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year 1 — Digital Design branch. Visual arts and communication using photography as the medium. Covers innovation, legal/copyright issues, worldwide communication, aesthetics (composition, light, image), and problem-solving. Students must provide their own digital camera.",
    tips:"Must have your own digital camera. Year 1 of the Digital Design branch within Arts & Media." },
  { id:"DIGDESIGN1", code:"TCD2000",   name:"Digital Design 1 (Photography 2)", dept:"CTE", ctePath:"Arts & Media", credits:1.0, gradeLevel:[10,11,12], prereqs:["DIGPHOTO1"], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year 2 — Digital Design branch. Equips students with skills to support and enhance digital media technology use. Topics: creating media content, communicative abilities, the production process, and legal concerns.",
    tips:"Completes 2-credit CTE requirement with Foundations. Great for media careers." },
  { id:"DIGDESIGN2", code:"TCD3000",   name:"Digital Design 2 (Directed Studies)", dept:"CTE", ctePath:"Arts & Media", credits:1.0, gradeLevel:[11,12], prereqs:["DIGDESIGN1"], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year 3 — Digital Design branch. Advanced knowledge/skill development beyond identified Programs of Study. Investigate, design, construct, and evaluate solutions to problems in the career pathway.",
    tips:"For students wanting deeper digital media skills beyond the core 2-course sequence." },

  // ── CTE — ARTS & MEDIA (Film & Media branch) ───────────────────────────────
  { id:"FILM_FOUND",code:"TCC1000MB", name:"Foundations of Creative Media (Film & Media)", dept:"CTE", ctePath:"Arts & Media", credits:1.0, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year 1 — Film & Media branch. Students learn tools, techniques, and terminology of television/video production. Hands-on filming, recording, and editing. Plans and produces short programs featuring topics of interest. Uses and compares nonlinear and other imaging/editing software.",
    tips:"Year 1 of the Film & Media branch. Hands-on TV/video production from day one." },
  { id:"FILM1",     code:"TCP2000",   name:"Film & Media Production 1 (Video Production Television 2)", dept:"CTE", ctePath:"Arts & Media", credits:1.0, gradeLevel:[10,11,12], prereqs:["FILM_FOUND"], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year 2 — Film & Media branch. Production of longer, more complex programs in a variety of formats. Script writing, storyboarding, taping, editing, and critical viewing and analysis. Prerequisite: Foundations of Creative Media.",
    tips:"Completes 2-credit CTE requirement with Foundations." },

  // ── CTE — ENGINEERING ──────────────────────────────────────────────────────
  { id:"ENG_FOUND",code:"TAE1000", name:"Foundations of Engineering Tech",    dept:"CTE", ctePath:"Engineering", credits:1.0, gradeLevel:[9,10,11], prereqs:[], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year 1. Teamwork, communication, ethics, and introductory industrial engineering technology. 3D printing, laser cutting, and CAD modeling in the rapid prototyping lab. Video, interactive activities, case studies, and project-based learning.",
    tips:"Year 1 of Engineering pathway. Hands-on tech lab — great for aspiring engineers." },
  { id:"ENG1",     code:"TAE2000", name:"Engineering Tech 1",                 dept:"CTE", ctePath:"Engineering", credits:1.0, gradeLevel:[10,11,12], prereqs:["ENG_FOUND"], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year 2. Drafting technology: design, spatial visualization, multi-view projection, auxiliaries, rotation, and computer-aided drafting. Prerequisite: Foundations of Engineering Tech.",
    tips:"Completes 2-credit CTE requirement. CAD skills are highly valued in engineering fields." },
  { id:"ENG2",     code:"TAE3000", name:"Engineering Tech 2",                 dept:"CTE", ctePath:"Engineering", credits:1.0, gradeLevel:[11,12], prereqs:["ENG1"], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year 3. Computer-aided design, mechanical/architectural/structural/electronics drawings and schematics. Real-world problem solving with industry-standard tools.",
    tips:"Requires Foundations and Engineering Tech 1. Great preparation for engineering college programs." },
  { id:"ENG3",     code:"TAE4000", name:"Engineering Technology 3",           dept:"CTE", ctePath:"Engineering", credits:1.0, gradeLevel:[12], prereqs:["ENG2"], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year 4. Civil, mechanical, and electrical engineering processes using hands-on real-world projects. Design innovation, manufacturing processes, and technical integration of reading/writing, math, and science.",
    tips:"Capstone engineering course. Requires all three prior courses in sequence." },

  // ── CTE — HEALTH SERVICES ──────────────────────────────────────────────────
  { id:"HLTH_FOUND",  code:"THF1000", name:"Foundations of Health Services",  dept:"CTE", ctePath:"Health Services", credits:1.0, gradeLevel:[9,10,11], prereqs:[], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year 1. Introduction to health careers, basic medical skills, and terminology. Foundation for Public Health Services, Diagnostic Services, Emergency Medical Services, Human Performance Therapeutic Services, and Nursing programs. Includes traditional Hawaiian healthcare philosophies and ethics. Students create a digital program of study portfolio.",
    tips:"Year 1 of Health Services pathway. Great starting point for medicine, nursing, or health careers." },
  { id:"ADV_HLTH",    code:"THA2000", name:"Advanced Health Services",        dept:"CTE", ctePath:"Health Services", credits:1.0, gradeLevel:[10,11,12], prereqs:["HLTH_FOUND"], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year 2. Human body structures and functions: how organs and body systems interplay. Virtual Portfolio development. Prerequisite: Foundations of Health Services.",
    tips:"Completes 2-credit CTE requirement. Strong foundation for nursing or pre-med tracks." },
  { id:"THERAPEUTIC", code:"THP3000", name:"Principles of Therapeutic Services", dept:"CTE", ctePath:"Health Services", credits:1.0, gradeLevel:[11,12], prereqs:["ADV_HLTH"], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year 3. Capstone. Work-based learning in therapeutic services. Hands-on practice in health-related fields. Students document logged clinical hours. Internship or work-placement component. Requires Foundations AND Advanced Health Services.",
    tips:"Includes an internship or clinical placement component. Capstone for Health Services pathway." },

  // ── CTE — CULINARY ARTS ────────────────────────────────────────────────────
  { id:"CULINARY1",   code:"TTU1000", name:"Foundations of Culinary Arts",    dept:"CTE", ctePath:"Culinary Arts", credits:1.0, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year 1. Introduction to food prep and service industry careers. Basic nutritional and cooking concepts. Hawaiian cultural influence on food. Proper safety protocols, commercial kitchen safety, nutrition, and cooking techniques. Students must wear shoes when required. Digital program of study portfolio created.",
    tips:"Year 1 of Culinary Arts pathway. Students must wear appropriate shoes in the kitchen." },
  { id:"CULINARY2",   code:"TTP2000", name:"Culinary Arts Food Preparation",  dept:"CTE", ctePath:"Culinary Arts", credits:1.0, gradeLevel:[10,11,12], prereqs:["CULINARY1"], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year 2. Basic food preparation methods in commercial kitchens and restaurants. Commercial kitchen safety and sanitation, menu planning, influence of culture, basic cooking principles, and platter/table presentation. Students must wear shoes. Digital portfolio maintained.",
    tips:"Completes 2-credit CTE requirement. Prerequisite: Foundations of Culinary." },
  { id:"CULINARY3",   code:"TTV3000", name:"Advanced Culinary Arts: Pastry and Savory", dept:"CTE", ctePath:"Culinary Arts", credits:1.0, gradeLevel:[11,12], prereqs:["CULINARY2"], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year 3. Fundamentals of pastry/dessert creations and meat preparation. Safe practices in a commercial kitchen, advanced culinary industry skills, digital portfolio continued. Prerequisite: Culinary Arts Food Preparation.",
    tips:"Year 3 of the Culinary Arts track. Focuses on pastry and savory techniques." },

  // ── CTE — COMPUTER SCIENCE ─────────────────────────────────────────────────
  { id:"CS_FOUND",code:"TIF1000", name:"Foundations of Computer Systems & Technology", dept:"CTE", ctePath:"Computer Science", credits:1.0, gradeLevel:[9,10,11], prereqs:["ALG1"], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year 1. Background in computer programming languages: analyze problems, write programs, prepare flow charts, and create documentation. CS's impact on society, global issues, and career exploration. Prerequisite: Credit in Algebra 1.",
    tips:"Algebra 1 required. Year 1 of the Computer Science pathway. Great stepping stone to AP Computer Science." },
  { id:"AP_CSA",  code:"ECS9500", name:"AP Computer Science A",               dept:"CTE", ctePath:"Computer Science", credits:1.0, gradeLevel:[10,11,12], prereqs:["CS_FOUND"], gradCategory:"wlfa", gradCredits:1.0, isAP:true,
    gradeReqs:{"CS_FOUND":"B or better"},
    desc:"Year 2 or 3 (offered in alternating years). Java programming, algorithms, data structures, and computer system components. AP exam required. B or better in CS Foundations (or credit in Computer A/B) AND teacher recommendation required. ⭐ CTE Honors requires both AP CSP AND AP CSA.",
    tips:"Offered alternating years with AP CSP. B+ in Foundations + teacher recommendation. CTE Honors requires BOTH AP CSP and AP CSA." },
  { id:"AP_CSP",  code:"ECS9800", name:"AP Computer Science Principles",      dept:"CTE", ctePath:"Computer Science", credits:1.0, gradeLevel:[10,11,12], prereqs:["CS_FOUND"], gradCategory:"wlfa", gradCredits:1.0, isAP:true,
    gradeReqs:{"CS_FOUND":"B or better"},
    desc:"Year 2 or 3 (offered in alternating years). Foundations of computing, data analysis, technology creation, and societal impact of CS. AP exam required. B or better in CS Foundations AND teacher recommendation required. ⭐ CTE Honors requires both AP CSP AND AP CSA.",
    tips:"More accessible than AP CS A. Offered alternating years. CTE Honors requires BOTH AP CSP and AP CSA." },

  // ── CTE — JROTC ────────────────────────────────────────────────────────────
  { id:"JROTC1",code:"TJC1000", name:"Coast Guard JROTC Maritime Science 1", dept:"CTE", ctePath:"JROTC", credits:1.0, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year 1. Coast Guard JROTC program: rights, responsibilities, leadership, physical fitness, drill, Coast Guard history and missions, government and citizenship. Community service and extracurricular competitions (marksmanship, Color Guard, rifle team). No military obligation. Completing Maritime Science I–III may qualify for college ROTC placement credit.",
    tips:"Two consecutive JROTC courses fulfill the 2-credit CTE graduation requirement. JROTC does NOT count toward CTE Honors." },
  { id:"JROTC2",code:"TJC2000", name:"Coast Guard JROTC Maritime Science 2", dept:"CTE", ctePath:"JROTC", credits:1.0, gradeLevel:[9,10,11,12], prereqs:["JROTC1"], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year 2. Leadership roles, oceanography, atmospheric science, maritime history. Selected cadets assist in unit instruction for Maritime Science 1. Positive SMSI/MSI Recommendation required. Uniform one school day per week.",
    tips:"Completes the 2-credit CTE graduation requirement. JROTC does NOT count toward CTE Honors." },
  { id:"JROTC3",code:"TJC3000", name:"Coast Guard JROTC Maritime Science 3", dept:"CTE", ctePath:"JROTC", credits:1.0, gradeLevel:[9,10,11,12], prereqs:["JROTC2"], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year 3. Problem-solving and decision-making in middle-management leadership positions. Staff briefings, Coast Guard operations, Search and Rescue. Cadets lead unit initiatives and provide instruction to junior cadets. Positive SMSI/MSI recommendation required.",
    tips:"Leadership-heavy year. Cadets take on instructional responsibilities for lower levels." },
  { id:"JROTC4",code:"TJC4000", name:"Coast Guard JROTC Maritime Science 4", dept:"CTE", ctePath:"JROTC", credits:1.0, gradeLevel:[9,10,11,12], prereqs:["JROTC3"], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year 4. Senior leadership and staff positions. Day-to-day unit operations, administrative and logistics files. Personal finance strategies and career readiness. Positive SMSI/MSI recommendation required regardless of service.",
    tips:"Highest JROTC level. Strong for college applications, especially military academies." },

  // ── WORLD LANGUAGE ─────────────────────────────────────────────────────────
  { id:"JPN1",  code:"WAJ1000",  name:"Japanese 1",          dept:"World Language", credits:1.0, gradeLevel:[9,10,11,12], prereqs:[],        gradCategory:"wlfa", gradCredits:1.0,
    desc:"Introductory Japanese. Basic vocabulary, grammar, social situations of daily life. K-3 benchmarks addressed. No prior experience needed.",
    tips:"Year 1. No experience required. Teacher signature required for Level 2 and above." },
  { id:"JPN2",  code:"WAJ2000",  name:"Japanese 2",          dept:"World Language", credits:1.0, gradeLevel:[9,10,11,12], prereqs:["JPN1"],  gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    desc:"Reinforces and builds on Japanese 1. Simple conversations, routine situations, cultural topics. Grade 4-5 benchmarks. Teacher signature required.",
    tips:"Completes 2-credit World Language requirement with Japanese 1. Standard track continues to Japanese 3." },
  { id:"JPN2H", code:"WAJ2000H", name:"Japanese 2 Honors",   dept:"World Language", credits:1.0, gradeLevel:[9,10,11,12], prereqs:["JPN1"],  gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    desc:"Accelerated second-year Japanese. Faster pace. Grade 4-8 benchmarks. Prepares students for Japanese 3 Honors and the AP track. Teacher/counselor approval required.",
    tips:"Choose this over Japanese 2 if you plan to pursue AP Japanese. Leads to Japanese 3 Honors." },
  { id:"JPN3",  code:"WAJ3000",  name:"Japanese 3",          dept:"World Language", credits:1.0, gradeLevel:[10,11,12], prereqs:["JPN2"],  gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    desc:"Expands listening, speaking, reading, and writing in Japanese. Students create with language and understand cultural nuances. Stage II Standards, grade 4-8 benchmarks. Teacher signature required.",
    tips:"Standard track. Leads to Japanese 4." },
  { id:"JPN3H", code:"WAJ3000H", name:"Japanese 3 Honors",   dept:"World Language", credits:1.0, gradeLevel:[10,11,12], prereqs:["JPN2H"], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    desc:"Accelerated third-year Japanese. Oral, written, and extended conversation. Prepares students for AP Japanese. Either successful completion of Level 2 Honors or Level 2 teacher recommendation required.",
    tips:"AP track course. Leads directly to AP Japanese. Level 2 Honors OR Level 2 teacher recommendation required." },
  { id:"JPN4",  code:"WAJ4000",  name:"Japanese 4",          dept:"World Language", credits:1.0, gradeLevel:[11,12],   prereqs:["JPN3"],  gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    desc:"Advanced Japanese. Extended conversation, narration, and description on varied topics. Stage II proficiencies, grade 6-8 benchmarks. Teacher signature required.",
    tips:"Standard track. Highest non-AP level of Japanese at Kalani." },
  { id:"AP_JPN",code:"WAJ6000",  name:"AP Japanese",         dept:"World Language", credits:1.0, gradeLevel:[11,12],   prereqs:["JPN3H"], gradCategory:"wlfa", gradCredits:1.0, isAP:true, teacherSigRequired:true,
    desc:"College-level Japanese. Active communication in reading, writing, listening, and speaking. Expository and persuasive writing compositions. AP exam required in May.",
    tips:"Requires Japanese 3 Honors. Strong grammar and vocabulary command needed." },
  { id:"SPN1",  code:"WES1000",  name:"Spanish 1",           dept:"World Language", credits:1.0, gradeLevel:[9,10,11,12], prereqs:[],       gradCategory:"wlfa", gradCredits:1.0,
    desc:"Introductory Spanish. Basic vocabulary, grammar, social situations. K-3 benchmarks. No prior experience needed.",
    tips:"Year 1. No experience required." },
  { id:"SPN2",  code:"WES2000",  name:"Spanish 2",           dept:"World Language", credits:1.0, gradeLevel:[9,10,11,12], prereqs:["SPN1"], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    desc:"Continues Spanish 1. More complex grammar and conversation. Grade 4-5 benchmarks. Teacher signature required.",
    tips:"Completes 2-credit World Language requirement with Spanish 1." },
  { id:"SPN3",  code:"WES3000",  name:"Spanish 3",           dept:"World Language", credits:1.0, gradeLevel:[10,11,12], prereqs:["SPN2"], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    desc:"Expands Spanish proficiency in all four skills. Stage II Standards, grade 4-8 benchmarks. Teacher signature required.",
    tips:"Good for students continuing Spanish. Teacher signature required." },
  { id:"SPN4",  code:"WES4000",  name:"Spanish 4",           dept:"World Language", credits:1.0, gradeLevel:[11,12],   prereqs:["SPN3"], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    desc:"Advanced Spanish. Extended conversation, narration, and description. Grade 6-8 benchmarks. Teacher signature required.",
    tips:"Highest level of Spanish at Kalani." },
  { id:"CHN1",  code:"WAC1000",  name:"Chinese 1",           dept:"World Language", credits:1.0, gradeLevel:[9,10,11,12], prereqs:[],       gradCategory:"wlfa", gradCredits:1.0,
    desc:"Introductory Mandarin Chinese. Basic vocabulary, grammar, social situations. K-3 benchmarks. No prior experience needed.",
    tips:"Year 1. No experience needed." },
  { id:"CHN2",  code:"WAC2000",  name:"Chinese 2",           dept:"World Language", credits:1.0, gradeLevel:[9,10,11,12], prereqs:["CHN1"], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    desc:"Continues Mandarin Chinese. Simple conversations and cultural topics. Grade 4-5 benchmarks. Teacher signature required.",
    tips:"Completes 2-credit World Language requirement with Chinese 1." },
  { id:"CHN3",  code:"WAC3000",  name:"Chinese 3",           dept:"World Language", credits:1.0, gradeLevel:[10,11,12], prereqs:["CHN2"], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    desc:"Expands Chinese proficiency in all four skills. Stage II Standards, grade 4-8 benchmarks. Teacher signature required.",
    tips:"Continues the Chinese sequence. Teacher signature required." },
  { id:"KOR1",  code:"WAK1000",  name:"Korean 1",            dept:"World Language", credits:1.0, gradeLevel:[9,10,11,12], prereqs:[],       gradCategory:"wlfa", gradCredits:1.0,
    desc:"Introductory Korean. Basic vocabulary, grammar, and social situations. K-3 benchmarks. No prior experience needed.",
    tips:"Year 1. New language offering at Kalani in 26-27. No experience required." },
  { id:"KOR2",  code:"WAK2000",  name:"Korean 2",            dept:"World Language", credits:1.0, gradeLevel:[9,10,11,12], prereqs:["KOR1"], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    desc:"Continues Korean. Conversations and cultural topics. Grade 4-5 benchmarks. Teacher signature required.",
    tips:"Completes 2-credit World Language requirement with Korean 1." },
  { id:"KOR3",  code:"WAK3000",  name:"Korean 3",            dept:"World Language", credits:1.0, gradeLevel:[10,11,12], prereqs:["KOR2"], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    desc:"Advanced Korean. Proficiency in all four skills. Stage II Standards, grade 4-8 benchmarks. Teacher signature required.",
    tips:"Continues the Korean sequence. Teacher signature required." },

  // ── FINE ARTS — VISUAL ─────────────────────────────────────────────────────
  { id:"ART1",        code:"FVB1000", name:"General Art 1",           dept:"Fine Arts", fineArtsType:"Visual", credits:1.0, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year course. Foundation: Elements and Principles of Design. Drawing, painting, printmaking (relief and stencil), and sculpture. Reflective analysis and critique are integral. Recommended as a foundation for other art courses. Open to all grade levels.",
    tips:"Foundation for all other visual art courses. Open to all grade levels. Highly recommended before Design 1 or other art courses." },
  { id:"ART2",        code:"FVB2000", name:"General Art 2",           dept:"Fine Arts", fineArtsType:"Visual", credits:1.0, gradeLevel:[9,10,11,12], prereqs:["ART1"], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    gradeReqs:{"ART1":"C or better"},
    desc:"Year course. Advanced skill refinement; self-directed projects and portfolio development. Emphasis on being a self-directed learner. C or better in General Art 1 and teacher signature required.",
    tips:"Completes 2-credit Fine Arts requirement with General Art 1. C or better + teacher signature required." },
  { id:"ART3",        code:"FVB3000", name:"General Art 3",           dept:"Fine Arts", fineArtsType:"Visual", credits:1.0, gradeLevel:[10,11,12], prereqs:["ART2"], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    gradeReqs:{"ART2":"C or better"},
    desc:"Year course. Further skill refinement. Emphasis on self-directed learning and portfolio expansion. C or better in General Art 2 and teacher signature required.",
    tips:"Teacher signature required. C or better in General Art 2. Can lead to AP 2D Art & Design." },
  { id:"DESIGN1",     code:"FVK1000", name:"Design 1",                dept:"Fine Arts", fineArtsType:"Visual", credits:1.0, gradeLevel:[9,10,11,12], prereqs:["ART1"], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    gradeReqs:{"ART1":"C or better"},
    desc:"Year course. Study and composition of visual elements. Graphic design, poster design, printmaking, fashion design. Uses Procreate and other digital programs. C or better in General Art 1 and teacher signature required.",
    tips:"Great for digital creatives. C or better in General Art 1 required." },
  { id:"DP1",         code:"FVQ1000", name:"Drawing & Painting 1",    dept:"Fine Arts", fineArtsType:"Visual", credits:1.0, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year course. Introductory drawing and painting. Art materials, techniques, and processes. Technical drawing skill development. Open to all grade levels.",
    tips:"Alternative foundation to General Art 1. Great for students focused on drawing and painting." },
  { id:"DP2",         code:"FVQ2000", name:"Drawing & Painting 2",    dept:"Fine Arts", fineArtsType:"Visual", credits:1.0, gradeLevel:[9,10,11,12], prereqs:["DP1"], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    gradeReqs:{"DP1":"B or better"},
    desc:"Year course. Advanced Drawing & Painting. B or better in Drawing & Painting 1 and teacher signature required.",
    tips:"Completes 2-credit Fine Arts requirement with Drawing & Painting 1. B or better required." },
  { id:"DP3",         code:"FVQ3000", name:"Drawing & Painting 3",    dept:"Fine Arts", fineArtsType:"Visual", credits:1.0, gradeLevel:[10,11,12], prereqs:["DP2"], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    gradeReqs:{"DP2":"B or better"},
    desc:"Year course. Advanced high-level realism techniques. For serious and/or college-bound art majors only. B or better in Drawing & Painting 2 and teacher signature required.",
    tips:"College-bound art majors. Prerequisite for AP 2D Art & Design (Drawing & Painting track)." },
  { id:"AP_2D",       code:"FVA3000", name:"AP 2D Art & Design",       dept:"Fine Arts", fineArtsType:"Visual", credits:1.0, gradeLevel:[11,12], prereqs:[], gradCategory:"wlfa", gradCredits:1.0, isAP:true, teacherSigRequired:true, concurrentOk:["DP3","ART3"],
    desc:"Year course. Highly advanced college-level 2D art and design. Portfolio submitted for AP exam. Two prerequisite tracks: Drawing & Painting 1-2-3 (can take concurrently with D&P 3, senior year), OR General Art 1-2-3 (can take concurrently with Art 3, senior year). Teacher signature required.",
    tips:"Can take concurrently with Drawing & Painting 3 or General Art 3 in senior year. Teacher signature required." },
  { id:"CER1",        code:"FVL1000", name:"Ceramics 1",               dept:"Fine Arts", fineArtsType:"Visual", credits:1.0, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year course. Hand-building: pinch pots, coils, and slabs. Glazing, surface decoration, communication in design. Students must supply some tools and materials. Initiative and independent work required.",
    tips:"No prior experience needed. Students must provide some supplies." },
  { id:"CER2",        code:"FVL2000", name:"Ceramics 2",               dept:"Fine Arts", fineArtsType:"Visual", credits:1.0, gradeLevel:[9,10,11,12], prereqs:["CER1"], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    gradeReqs:{"CER1":"C or better"},
    desc:"Year course. Refining ceramics skills. Wheel throwing introduced. More independent work. C or better in Ceramics 1 and teacher signature required.",
    tips:"Completes 2-credit Fine Arts requirement with Ceramics 1. C or better required." },
  { id:"CER3",        code:"FVL3000", name:"Ceramics 3",               dept:"Fine Arts", fineArtsType:"Visual", credits:1.0, gradeLevel:[10,11,12], prereqs:["CER2"], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    gradeReqs:{"CER2":"C or better"},
    desc:"Year course. Exploring advanced ceramics techniques. Build art portfolio and participate in art exhibitions. C or better in Ceramics 2 and teacher signature required.",
    tips:"Portfolio-building course. Great for students pursuing art seriously." },
  { id:"DIR_ART",     code:"FVD1000", name:"Directed Studies Art",     dept:"Fine Arts", fineArtsType:"Visual", credits:1.0, gradeLevel:[10,11,12], prereqs:[], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    desc:"Year course. Requires successful completion of a level 2 or 3 art course and instructor consent. Serious commitment to personal growth and expression in visual arts. Thoughtful, focused, and informed decision-making. Preparation for rigorous self-direction.",
    tips:"Requires a level 2 or 3 art course in your history. Instructor consent and signature required." },

  // ── FINE ARTS — PERFORMING ─────────────────────────────────────────────────
  { id:"BAND",       code:"FMB2000", name:"Band 1–4",                  dept:"Fine Arts", fineArtsType:"Performing", credits:1.0, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"wlfa", gradCredits:1.0, repeatable:true, teacherSigRequired:true,
    desc:"Year course (repeatable through 4 years). THIS IS NOT AN INTRODUCTORY COURSE. Requires two consecutive years of middle school band or 18 consecutive months of private instruction on the same instrument. Students provide their own mouthpieces, reeds, and basic percussion sticks and mallets. Three major performances + one individual/small group performance per year. Signature from current band director required.",
    tips:"Must have prior band experience. Not for beginners. Band director signature required for enrollment." },
  { id:"ORCH",       code:"FMV2000", name:"Orchestra 1–4",             dept:"Fine Arts", fineArtsType:"Performing", credits:1.0, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"wlfa", gradCredits:1.0, repeatable:true, teacherSigRequired:true,
    desc:"Year course (repeatable). THIS IS NOT AN INTRODUCTORY COURSE. Two consecutive years of orchestra or 18 consecutive months of private instruction required. Advanced techniques and orchestral literature. After-school rehearsals and proficiency assessments expected. Selected to perform with Concert Orchestra.",
    tips:"Must have prior orchestra experience. Not for beginners. After-school performances and rehearsals required." },
  { id:"CHORUS1",    code:"FMC1000", name:"Chorus 1",                  dept:"Fine Arts", fineArtsType:"Performing", credits:1.0, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year course. Beginning vocal techniques: tone quality, breath support, posture, diction. Wide range of musical styles including Sacred, Classical, Folk, Hawaiian, Oldies, Rock, Hip-Hop, Opera, Pop, and Seasonal. No prerequisites. Students must perform in formal concerts.",
    tips:"No experience needed. Great way to fulfill Fine Arts credit while performing music." },
  { id:"CHORUS2",    code:"FMC2000", name:"Chorus 2–4",                dept:"Fine Arts", fineArtsType:"Performing", credits:1.0, gradeLevel:[9,10,11,12], prereqs:["CHORUS1"], gradCategory:"wlfa", gradCredits:1.0, repeatable:true,
    desc:"Year course (repeatable for years 2–4). Continues vocal development: advanced techniques, expanded tone quality, stage performance, and community service concerts. Teacher approval required to move to next level.",
    tips:"Continues each year with more advanced performance responsibilities." },
  { id:"DANCE",      code:"FDC1000", name:"Creative Dance 1–3",        dept:"Fine Arts", fineArtsType:"Performing", credits:1.0, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"wlfa", gradCredits:1.0, repeatable:true,
    desc:"Year course (repeatable for years 1–3). Students choreograph their own dance routines across styles: ballet, street dance, group/partner dancing. Two recitals per year required. Body awareness, strength, flexibility, and performance skills. Students MUST PARTICIPATE in all styles and MUST PERFORM at two recitals.",
    tips:"Open to all students. Must perform in two recitals per year." },
  { id:"DANCE4",     code:"FDD1100", name:"Creative Dance 4th Year (Directive Studies)", dept:"Fine Arts", fineArtsType:"Performing", credits:1.0, gradeLevel:[12], prereqs:["DANCE"], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    desc:"Year course. Fourth-year continuation of the Creative Dance program. Independent, self-directed choreography and performance work at an advanced level. Teacher signature required.",
    tips:"Year 4 of Creative Dance. Requires completion of Creative Dance 1–3. Teacher signature required." },
  { id:"PIANO1",     code:"FMK1000", name:"Piano 1",                   dept:"Fine Arts", fineArtsType:"Performing", credits:1.0, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    desc:"Year course. Basic piano knowledge and skills. Students will be involved in reading, performing, and evaluating piano music. Public performance REQUIRED at year end and possibly at semester end. Class size is limited. Teacher approval required.",
    tips:"Teacher approval required. Public performance at year end. Limited class size — sign up early." },
  { id:"PIANO2",     code:"FMK2000", name:"Piano 2–4",                 dept:"Fine Arts", fineArtsType:"Performing", credits:1.0, gradeLevel:[9,10,11,12], prereqs:["PIANO1"], gradCategory:"wlfa", gradCredits:1.0, repeatable:true, teacherSigRequired:true,
    desc:"Year course (repeatable). Continues Piano 1 with advanced music theory, technique, and performance. Concert performances required. Class size limited. Teacher approval required. Open to students who have completed Piano 1 or have prior private piano study.",
    tips:"Teacher approval required. Limited class size. Can continue each year for additional credits." },
  { id:"POLY_MUSIC", code:"FMP1000", name:"Polynesian Music & Dance 1–4", dept:"Fine Arts", fineArtsType:"Performing", credits:1.0, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"wlfa", gradCredits:1.0, repeatable:true,
    desc:"Year course (repeatable through 4 years). Music and dances of the Polynesian archipelago. Cultural, social, historical, and expressive significance. Emphasis on authentic foot and body movement, costume.",
    tips:"Open to all students. Unique Hawaiian cultural experience. Excellent Fine Arts elective." },
  { id:"UKULELE1",   code:"FML1000", name:"Ukulele 1",                 dept:"Fine Arts", fineArtsType:"Performing", credits:1.0, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"wlfa", gradCredits:1.0,
    desc:"Year course. Introductory ukulele: performing, listening to, and evaluating ukulele music. Students develop skills in reading, performing, and cultural appreciation.",
    tips:"No prior experience needed. Great way to connect with Hawaiian culture through music." },
  { id:"UKULELE2",   code:"FML2000", name:"Ukulele 2", repeatable:true,                 dept:"Fine Arts", fineArtsType:"Performing", credits:1.0, gradeLevel:[9,10,11,12], prereqs:["UKULELE1"], gradCategory:"wlfa", gradCredits:1.0, teacherSigRequired:true,
    desc:"Year course. Continues development of ukulele playing skills. Listening, performing, and evaluating at a higher level. Teacher approval required. Class size limited.",
    tips:"Must complete Ukulele 1 first. Teacher approval required. Class size limited — sign up early." },

  // ── ELL (English Language Learners) ────────────────────────────────────────
  { id:"ELL_COMM",  code:"NEI1000", name:"Communication & Literacy Skills for Newcomers", dept:"Miscellaneous", miscType:"ESOL", credits:1.0, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"electives", gradCredits:1.0,
    desc:"Two-semester course (NEI1000 Semester A + NEI1010 Semester B). Designed for non-native English speakers new to the U.S. school system. Develops basic English language skills in reading, writing, speaking, and listening. Introduces American school culture and community. NOT repeatable. Placement by NEP 1.0+ ICY designation or EL Teacher recommendation.",
    tips:"⚠️ Assigned by administration based on language screening. Not self-selected. Counts as elective credit toward graduation." },
  { id:"ELL_ESOL1", code:"NEI1020", name:"English for Speakers of Other Languages 1A/1B", dept:"Miscellaneous", miscType:"ESOL", credits:1.0, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"electives", gradCredits:1.0, repeatable:true,
    desc:"Two-semester course (NEI1020 Semester 1A + NEI1025 Semester 1B). Beginning English language sequence. Social instructional English, reading, and writing fundamentals. Basic English grammar instruction. Repeatable for credit. Placement by NEP 1.0+ or EL Teacher recommendation.",
    tips:"⚠️ Assigned by administration. Repeatable for credit. Counts as elective credit toward graduation." },
  { id:"ELL_ESOL2", code:"NEI1030", name:"English for Speakers of Other Languages 2A/2B", dept:"Miscellaneous", miscType:"ESOL", credits:1.0, gradeLevel:[9,10,11,12], prereqs:[], gradCategory:"electives", gradCredits:1.0, repeatable:true,
    desc:"Two-semester course (NEI1030 Semester 2A + NEI1035 Semester 2B). Second level of English language development. More challenging content, reading, writing, and academic language for integrated content courses. Repeatable for credit. Placement by LEP 3.0+ or EL Teacher recommendation.",
    tips:"⚠️ Assigned by administration. Repeatable for credit. Counts as elective credit toward graduation." },

  // ── OFF CAMPUS ──────────────────────────────────────────────────────────────
  { id:"OFF_CAMPUS", code:"", name:"Off Campus Period", dept:"Off Campus", credits:0, gradeLevel:[12], prereqs:[],
    gradCategory:null, gradCredits:0, repeatable:true, isOffCampus:true,
    eligibility:[
      "Met ALL graduation requirements (except ELA 12 & Social Studies)",
      "Completed the Personal Transition Plan (PTP)",
      "Have a qualifying reason (see below)",
    ],
    reasons:[
      { label:"✅ Early graduation (Semester A only)", limit:"One semester maximum — Grade 12 Sem A only" },
      { label:"🟡 Work study / employment during school day", limit:"Requires proof of employment + counselor approval" },
    ],
    submissions:[
      "Google Off Campus Request Form (submitted online)",
      "Parent/guardian signature on the request form",
      "Counselor approval prior to off campus period",
    ],
    warning:"Off Campus approval is not automatic. All three eligibility conditions must be met and administrative approval granted.",
    deadline:"See counselor for current deadline",
    tips:"Check with your counselor early in senior year to confirm eligibility and start the approval process." },
];

const DEPTS = [
  "All","English","Social Studies","Mathematics","Science",
  "Health & PE","CTE","World Language","Fine Arts","Miscellaneous","Off Campus"
];

const CTE_PATHS = ["All CTE","AFNR","Business","Arts & Media","Engineering","Health Services","Culinary Arts","Computer Science","JROTC"];

const FINE_ARTS_TYPES = ["All Fine Arts","Performing","Visual"];

const MISC_TYPES = ["All Miscellaneous","General","Journalism","ESOL"];

const DEPT_COLORS = {
  "English":"#C84B31","Social Studies":"#7C3AED","Mathematics":"#059669",
  "Science":"#D97706","Health & PE":"#0891B2","CTE":"#B00804",
  "World Language":"#0284C7","Fine Arts":"#DB2777",
  "Miscellaneous":"#6B7280","Off Campus":"#475569",
};

const DEFAULT_PLAN = {
  9:  ["GEO","ELA1","PID","MHH","ISCI","PE_LF","HEALTH"],
  10: ["ALG1","ELA2","USH","BIO1_10","PE_LA","JPN1"],
  11: ["ALG2","ELA3","WH","HCHEM","JPN2","PTP"],
  12: ["TRIG","ELA4","ECON","PSYCH","MARINE"],
};

const PREREQ_EQUIV = {
  "BIO1_10": ["BIO1_9"],
  "BIO1_9":  ["BIO1_10"],
  "CHEM":    ["HCHEM"],
  "USH":     ["AP_USH"],
  "WH":      ["AP_WH"],
  "ELA3":    ["AP_ENG3"],
  "JPN2":    ["JPN2H"],
  "JPN3":    ["JPN3H"],
};

const HONORS_DEFS = [
  {
    id: "academic",
    label: "Academic Honors",
    color: "#7C3AED",
    icon: "\ud83c\udf96",
    description: "Cumulative GPA 3.500+ required",
    checks: [
      { id:"math4", label:"4 credits Math (Algebra 2 + one beyond)", desc:"Algebra 2 + one of: Trig/PreCal, Alg3/Stats, Calculus, AP Calculus, AP Stats, AP CS A, AP CS Principles, Intro to College Math" },
      { id:"sci4",  label:"4 credits Science (incl. Biology 1)",     desc:"Biology 1 + 3 other science credits" },
      { id:"ap2",   label:"2+ AP/IB/Running Start credits",          desc:"At least 2 credits from AP, IB, or Running Start courses" },
    ],
  },
  {
    id: "stem",
    label: "STEM Honors",
    color: "#0891B2",
    icon: "\ud83d\udd2c",
    description: "Cumulative GPA 3.500+ required",
    checks: [
      { id:"math4",    label:"4 credits Math (Algebra 2 + one beyond)", desc:"Same math requirement as Academic Honors" },
      { id:"sci4",     label:"4 credits Science (incl. Biology 1)",     desc:"Same science requirement as Academic Honors" },
      { id:"stem_cap", label:"STEM Capstone Project (XAT1000)",         desc:"Successful completion of STEM Capstone. Required for class of 2016 and beyond." },
    ],
  },
  {
    id: "cte",
    label: "CTE Honors",
    color: "#B00804",
    icon: "\ud83d\udee0",
    description: "Cumulative GPA 3.0+ required",
    checks: [
      { id:"cte_seq",  label:"Complete 2–3 course CTE pathway sequence", desc:"2-3 courses in the same approved CTE pathway with B or better in each. \u26a0\ufe0f Computer Science pathway requires BOTH AP CSP AND AP CSA. JROTC courses do NOT count toward CTE Honors." },
      { id:"cte_perf", label:"Meet/exceed proficiency on performance assessment", desc:"Assessed per program of study by teacher — cannot be tracked here." },
    ],
  },
];

const BEYOND_ALG2_IDS = ["TRIG","ALG3","CALC","AP_CALC","AP_STATS","AP_CSA","AP_CSP","ICMATH"];

export {
  COURSES,
  GRAD_REQUIREMENTS,
  PREREQ_EQUIV,
  HONORS_DEFS,
  BEYOND_ALG2_IDS,
  DEPTS,
  CTE_PATHS,
  FINE_ARTS_TYPES,
  MISC_TYPES,
  DEPT_COLORS,
  DEFAULT_PLAN,
  DEPT_ORDER,
};
